DELETE http://localhost:3003/api/blogs/4

###

GET http://localhost:3003/api/blogs
###
POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "How to ...",
  "author": "Bob",
  "url": "https://en.wikipedia.org/wiki/Blog",
  "likes": 1 
}